[package]
name = "gapi_grpc"
version = "0.0.7"
authors = ["Konosuke Kachi <github@s.k-kachi.net>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/gkkachi/gapi-grpc-rs"
documentation = "https://gkkachi.github.io/gapi-grpc-rs"
description = """
A gRPC client library for Google APIs, generated automatically from the API definition files.
"""
keywords = ["gapi", "grpc", "gcp", "firebase", "tonic"]

[lib]

[dependencies]
tonic = { version = "0.2", features = ["tls", "tls-roots"] }
prost = "0.6"
prost-types = "0.6"

[build-dependencies]
tonic-build = "0.2"
