steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - "-c"
  - "gcloud secrets versions access latest --secret=CRATES_IO_TOKEN > CRATES_IO_TOKEN"

- name: gcr.io/cloud-builders/docker
  args:
  - "run"
  - "-v"
  - "/workspace:/usr/src/myapp"
  - "-w"
  - "/usr/src/myapp"
  - "rust:slim"
  - "bash"
  - "-c"
  - "rustup component add rustfmt && cargo login `cat CRATES_IO_TOKEN` && cargo publish"
options:
  machineType: 'N1_HIGHCPU_32'
